### ISSUE TITLE
[Documentation] Custom start page

### ISSUE THREAD

**Issue by BlackLotus** [Speyll/void-bspwm#6]
Heyho what custom start page are you using? Is that a firefox addons that lets you set a custom html file or is this a page? Is this "just" a custom css set through `legacyUserProfileCustomizations`? Was just wondering...

**Comment by Speyll** [comment]
Yo, actually, it's neither. (well I guess it's kinda a custom html file?) I built a personal website and host it using Pages (Gitlab or GitHub Pages if you don’t mind it being public, though you can add Cloudflare to keep it private and still have the Pages aspect). I then just set the URL as my homepage in `about:preferences#home` on Firefox. This way, I can access the startpage on any device with internet access.

If you prefer a more local setup, you can host the site locally. For example, you could use something lightweight like [thttpd](https://acme.com/software/thttpd/) to serve the page at pc startup or with a simple command, then set the local URL as the homepage, that’s how I’d do it I’m not a fan of relying too much on extensions, hope this helped 🙂

**Comment by BlackLotus** [comment]
Actually you could set the HTML page as well with file:/// 
I thought you didn't use this because the url was missing from your screenshot, but you probably just deleted it for the screenshot. Anyway thx for clearling that up :)
